AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An example Lambda function using the Secrets Manager Lambda Extension with container image

#When you "sam build" it will ask you to provide a name for your secret. The default is "MySecret"
Parameters:
  SecretName:
    Description: Secret Name
    Type: String
    Default: MySecret
    AllowedPattern: ^[a-zA-Z0-9_.-/]*$

Resources:
  #Make a secret
  MySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Ref SecretName
      Description: "Secret with dynamically generated secret password."
      GenerateSecretString:
        PasswordLength: 30
        ExcludeCharacters: '"@/\'

  #Make a lambda function
  SecretsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
          PARAMETERS_SECRETS_EXTENSION_HTTP_PORT: "2773" #2773 is the default, but we go ahead and explicility set it to the default value anyways
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref MySecret
    Metadata:
      DockerTag: latest
      DockerContext: ./
      Dockerfile: Dockerfile

      

Outputs:
  MySecret:
    Value: !Ref MySecret
    Description: MySecret ARN
  MySecretName:
    Value: !Ref SecretName
    Description: SecretName

